### PR TITLE
Fixed #178 : Improved 'connect failed' error msgs

### LINKED ISSUE #178: CIS needs to give more useful information messages during CIS startup, if connection failed etc.
CIS needs to give more useful information messages during CIS startup, if connection failed etc.
eg: When CIS connection to memory server fails - it would be helpful to print - to which memory server or metadata server -instead of just printing connect failed

### PR DESCRIPTION
**Pull request by cynara-justine**
Fixed #178 : Improved 'connect failed' error msgs

### CODE REVIEW

File: src/cis/fam_cis_client.cpp [hunk 1]
```diff
@@ -54,7 +54,8 @@ Fam_CIS_Client::Fam_CIS_Client(const char *name, uint64_t port) {
     /** sending a start signal to server **/
     ::grpc::Status status = stub->signal_start(&ctx, req, &res);
     if (!status.ok()) {
-        throw CIS_Exception(FAM_ERR_RPC, (status.error_message()).c_str());
+        message << "Fam CIS Client: Connect failed : "<<name_s;
```
Comment (mashoodk) [inline src/cis/fam_cis_client.cpp:57]: Here we will need to get the output from GRPC too. Probably something like :
status.error_message()).c_str() + ":" + name_s

**Review by mashoodk — CHANGES_REQUESTED** [review]

File: src/cis/fam_cis_client.cpp (hunk 1 above)
Comment (cynara-justine) [reply src/cis/fam_cis_client.cpp]: Modified code to address the review comment.  Earlier, when including output from GRPC, there was duplication of 'Connect Failed' as shown below. "Error msg: Fam Memory Service: Connect failed : Connect Failed:127.0.0.1:8795".  Therefore, I had not added grpc error code in the original PR to prevent duplication..
Now, I have modified code in such a way that, OpenFAM does not print the duplicate 'Connect Failed' and only the 'Connect Failed' from grpc is printed.
The net effect in the final error message output remains unchanged as in the following example:
Error msg: Fam Memory Service: Connect Failed:127.0.0.1:8795

**Review by mashoodk — APPROVED** [review]

**Review by faizan-barmawer — APPROVED** [review]
Code looks fine.
